apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: crashy-app.rules
    rules:
    - alert: PodRestartTooOften
      expr: changes(kube_pod_container_status_restarts_total{namespace="default", pod=~"crashy-app.*"}[5m]) > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} has restarted {{ $value }} times in 5m"
        description: "This may indicate application crash loop."