apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  namespace: monitoring
  labels:
    release: prometheus  # Wajib! Agar Prometheus deteksi
spec:
  groups:
    - name: pod-restart.rules
      rules:
        - alert: PodRestartTooOften
          expr: |
            changes(
              kube_pod_container_status_restarts_total{namespace="default"}[5m]
            ) > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} restarted {{ $value }} times in 5 minutes"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 5 times in the last 5 minutes. This may indicate a crash loop."